name 'mobilitymap'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mobilitymap'
long_description 'Installs/Configures mobilitymap'
version '0.1.0'

depends 'poise-python'
#depends 'postgresql'
